export interface Entreprise {
  nom: string
  secteur: string
  type: 'BtoB' | 'BtoC' | 'BtoBtoC'
  exemple: string
}

export const entreprises: Entreprise[] = [
  { nom: 'Airbus', secteur: 'Aéronautique', type: 'BtoB', exemple: 'Vend des avions à Air France, pas aux passagers' },
  { nom: 'Michelin', secteur: 'Pneumatiques', type: 'BtoB', exemple: 'Fournit des pneus à Renault et aux flottes pro' },
  { nom: 'Salesforce', secteur: 'Logiciel CRM', type: 'BtoB', exemple: 'Vend ses outils aux équipes commerciales des entreprises' },
  { nom: 'Manpower', secteur: 'RH / Intérim', type: 'BtoB', exemple: 'Propose des profils à recruter aux entreprises clientes' },
  { nom: 'Dassault Systèmes', secteur: 'Logiciel industriel', type: 'BtoB', exemple: 'Conçoit des logiciels de simulation pour Airbus et Boeing' },
  { nom: 'Schneider Electric', secteur: 'Énergie', type: 'BtoB', exemple: 'Fournit des tableaux électriques à des usines et data centers' },
  { nom: 'Carrefour', secteur: 'Grande distribution', type: 'BtoC', exemple: 'Vend directement aux consommateurs en magasin' },
  { nom: 'Fnac', secteur: 'Retail high-tech', type: 'BtoC', exemple: 'Vend des appareils électroniques au grand public' },
  { nom: 'Netflix', secteur: 'Streaming', type: 'BtoC', exemple: 'Abonnement vendu directement aux particuliers' },
  { nom: 'Zara', secteur: 'Mode', type: 'BtoC', exemple: 'Vend ses vêtements directement en boutique et en ligne' },
  { nom: 'BNP Paribas', secteur: 'Banque', type: 'BtoBtoC', exemple: 'Sert les particuliers ET les entreprises' },
  { nom: 'Orange', secteur: 'Télécom', type: 'BtoBtoC', exemple: 'Offre des forfaits aux particuliers et des réseaux aux entreprises' },
  { nom: 'Amazon', secteur: 'E-commerce / Cloud', type: 'BtoBtoC', exemple: 'Vend au grand public ET des services cloud (AWS) aux entreprises' },
  { nom: 'Deloitte', secteur: 'Conseil / Audit', type: 'BtoB', exemple: 'Accompagne des grandes entreprises dans leur stratégie et comptabilité' },
  { nom: 'L\'Oréal', secteur: 'Cosmétiques', type: 'BtoBtoC', exemple: 'Vend en GMS au grand public et des gammes pro aux coiffeurs' },
  { nom: 'Sodexo', secteur: 'Services', type: 'BtoB', exemple: 'Gère les cantines et services aux entreprises, pas aux salariés directement' },
  { nom: 'EDF', secteur: 'Énergie', type: 'BtoBtoC', exemple: 'Fournit de l\'électricité aux ménages ET aux industriels' },
  { nom: 'LVMH', secteur: 'Luxe', type: 'BtoC', exemple: 'Vend directement aux clients finaux via ses maisons (Dior, Vuitton…)' },
  { nom: 'Saint-Gobain', secteur: 'Matériaux', type: 'BtoB', exemple: 'Fournit du verre et des isolants aux constructeurs et artisans' },
  { nom: 'Capgemini', secteur: 'Conseil IT', type: 'BtoB', exemple: 'Développe des systèmes d\'information pour les grandes entreprises' },
]

export const conseilsCV: string[] = [
  'Adapte ton CV à chaque offre : relis la fiche de poste et utilise les mêmes mots-clés.',
  'Limite ton CV à une seule page pour un profil junior ou en cours de formation.',
  'Commence chaque expérience par un verbe d\'action fort : "Développé", "Géré", "Animé", "Analysé".',
  'Chiffre tes réalisations dès que possible : "Augmenté le CA de 15 %", "Géré une équipe de 4 personnes".',
  'Ne mens jamais : toute compétence mentionnée peut faire l\'objet d\'une question en entretien.',
  'Soigne le design : lisible, aéré, cohérent. Évite les couleurs criardes et les photos non demandées.',
  'Indique un email professionnel (prénom.nom@), pas "surfer2005@...".',
  'Mets ton profil LinkedIn à jour et ajoute l\'URL sur ton CV.',
  'Relis 3 fois et fais relire par quelqu\'un d\'autre : une faute peut éliminer un candidat.',
  'Place les informations les plus importantes en haut de page : le recruteur scanne en 6 secondes.',
  'Évite les phrases longues : des mots-clés et des formulations percutantes suffisent.',
  'Indique le niveau de langue réel : "Anglais courant" si tu l\'es vraiment, pas pour faire bien.',
]

export const astuceRecruteur: string[] = [
  'Je scanne un CV en moins de 10 secondes avant de décider de le lire en entier.',
  'Un email ou numéro de téléphone manquant, et je passe au suivant sans te contacter.',
  'Les fautes d\'orthographe me donnent une image négative, même pour un poste non rédactionnel.',
  'Un trou non expliqué dans un parcours m\'interroge toujours — autant l\'anticiper dans la lettre.',
  '"Passionné par les challenges" ne veut rien dire. Donne des exemples concrets à la place.',
]

export interface Situation {
  id: number
  situation: string
  optionA: string
  feedbackA: string
  optionB: string
  feedbackB: string
  optionC: string
  feedbackC: string
  bonneOption: 'A' | 'B' | 'C'
}

export const situations: Situation[] = [
  {
    id: 1,
    situation: 'Votre responsable vous demande de falsifier un document officiel.',
    optionA: 'Vous refusez poliment mais fermement, en expliquant que ce n\'est pas légal.',
    feedbackA: 'Bonne réaction. Refuser une tâche illégale est non seulement justifié, mais obligatoire. Vous pouvez proposer de trouver une solution alternative légale.',
    optionB: 'Vous exécutez la demande pour ne pas contrarier votre supérieur.',
    feedbackB: 'Très risqué. Vous êtes co-responsable d\'un acte illégal. Cela peut avoir des conséquences pénales pour vous, même en stage.',
    optionC: 'Vous faites semblant d\'accepter, puis n\'exécutez pas.',
    feedbackC: 'Cette posture passive peut aggraver la situation. Il vaut mieux exprimer clairement votre refus et vos raisons.',
    bonneOption: 'A',
  },
  {
    id: 2,
    situation: 'Un client vous pose une question à laquelle vous ne savez pas répondre.',
    optionA: 'Vous inventez une réponse pour ne pas paraître incompétent.',
    feedbackA: 'Risqué. Donner une fausse information peut nuire au client et à l\'image de l\'entreprise. La vérité rattrape toujours.',
    optionB: 'Vous lui dites honnêtement que vous allez vous renseigner et que vous le rappelez.',
    feedbackB: 'Excellente attitude. Reconnaître ses limites et s\'engager à trouver la bonne réponse est perçu positivement par les clients.',
    optionC: 'Vous raccrochez ou fuyez la conversation.',
    feedbackC: 'Fuir n\'est jamais professionnel. Le client reste sans réponse et l\'image de l\'entreprise en pâtit.',
    bonneOption: 'B',
  },
  {
    id: 3,
    situation: 'Vous êtes en retard de 20 minutes à votre premier jour de stage.',
    optionA: 'Vous arrivez sans rien dire, en espérant que personne ne l\'a remarqué.',
    feedbackA: 'Mauvaise stratégie. Le silence face à un retard est perçu comme un manque de responsabilité. Mieux vaut expliquer et s\'excuser.',
    optionB: 'Vous appelez avant d\'arriver pour prévenir et vous excuser.',
    feedbackB: 'Parfait. Prévenir à l\'avance montre votre professionnalisme et votre respect pour les autres. Tout le monde peut avoir un imprévu.',
    optionC: 'Vous inventez une fausse excuse très élaborée.',
    feedbackC: 'Mentir peut se retourner contre vous si l\'excuse est vérifiée ou peu crédible. La vérité simple avec des excuses sincères est bien plus efficace.',
    bonneOption: 'B',
  },
  {
    id: 4,
    situation: 'Un collègue prend tout le crédit de votre travail lors d\'une réunion.',
    optionA: 'Vous dites immédiatement et agressivement devant tout le monde que c\'est votre travail.',
    feedbackA: 'Une confrontation directe en public peut créer des tensions inutiles. Il vaut mieux choisir un moment et un ton plus appropriés.',
    optionB: 'Vous ne dites rien pour éviter le conflit.',
    feedbackB: 'Le silence peut s\'installer comme une habitude. À terme, votre contribution risque d\'être systématiquement ignorée.',
    optionC: 'Vous intervenez calmement pour apporter votre éclairage sur votre part dans le projet.',
    feedbackC: 'Bonne approche. Recadrer diplomatiquement les faits sans agressivité est la marque d\'un bon professionnel.',
    bonneOption: 'C',
  },
  {
    id: 5,
    situation: 'On vous confie une tâche dont vous ne comprenez pas les instructions.',
    optionA: 'Vous faites de votre mieux sans poser de question pour ne pas paraître incompétent.',
    feedbackA: 'Risqué. Vous risquez de produire un travail inutilisable. Poser des questions en début de mission est toujours préférable.',
    optionB: 'Vous demandez des précisions immédiatement, en reformulant ce que vous avez compris.',
    feedbackB: 'Excellent réflexe. Reformuler montre que vous êtes engagé et évite les malentendus coûteux en temps.',
    optionC: 'Vous attendez la deadline pour avouer que vous n\'aviez pas compris.',
    feedbackC: 'Attendre crée un problème de délai en plus du problème de compréhension. Plus tôt vous signalez le problème, plus il est facile à résoudre.',
    bonneOption: 'B',
  },
  {
    id: 6,
    situation: 'Un client est très agressif au téléphone et vous insulte.',
    optionA: 'Vous lui répondez sur le même ton.',
    feedbackA: 'Jamais. Même face à un client irrespectueux, escalader le conflit peut nuire à l\'entreprise et à vous-même.',
    optionB: 'Vous restez calme, reconnaissez sa frustration, et proposez une solution ou un transfert vers un supérieur.',
    feedbackB: 'Très professionnel. Garder son calme face à l\'agressivité est une compétence clé de la relation client.',
    optionC: 'Vous raccrochez sans un mot.',
    feedbackC: 'Raccrocher sans explication laisse le client sans solution. Un bref "je vais vous transférer vers quelqu\'un qui pourra vous aider" est plus adapté.',
    bonneOption: 'B',
  },
  {
    id: 7,
    situation: 'Vous remarquez une erreur dans un document déjà envoyé à un client.',
    optionA: 'Vous attendez de voir si le client la remarque.',
    feedbackA: 'Attendre expose l\'entreprise à une perte de crédibilité plus grande si le client découvre l\'erreur avant vous.',
    optionB: 'Vous la signalez immédiatement à votre responsable et proposez une correction.',
    feedbackB: 'Bonne réaction. Reconnaître et corriger rapidement une erreur renforce la confiance et votre fiabilité.',
    optionC: 'Vous modifiez silencieusement le document original sans en informer personne.',
    feedbackC: 'Modifier un document déjà envoyé sans signalement peut créer des incohérences et nuire à la traçabilité.',
    bonneOption: 'B',
  },
  {
    id: 8,
    situation: 'Votre responsable vous confie une mission trop importante pour votre niveau.',
    optionA: 'Vous acceptez sans rien dire et espérez vous en sortir.',
    feedbackA: 'Risqué. Si vous échouez, l\'impact sera négatif pour vous et l\'entreprise. Il vaut mieux prévenir tôt.',
    optionB: 'Vous exprimez vos doutes, demandez un accompagnement, et acceptez l\'objectif en étant honnête sur vos limites.',
    feedbackB: 'Parfait. Être transparent sur ses capacités tout en montrant de la bonne volonté est mature et professionnel.',
    optionC: 'Vous refusez catégoriquement.',
    feedbackC: 'Un refus sec peut être perçu comme un manque d\'ambition. Mieux vaut accepter avec des garde-fous et du soutien.',
    bonneOption: 'B',
  },
  {
    id: 9,
    situation: 'Un collègue vous demande de couvrir son absence non justifiée.',
    optionA: 'Vous acceptez pour lui rendre service.',
    feedbackA: 'Vous vous rendez complice d\'une faute. Si cela est découvert, vous en portez aussi la responsabilité.',
    optionB: 'Vous refusez gentiment et lui expliquez que vous ne pouvez pas prendre ce risque.',
    feedbackB: 'Bonne réaction. Il est normal de refuser de se mettre dans une position de mensonge pour quelqu\'un d\'autre.',
    optionC: 'Vous délatez immédiatement le collègue auprès de la direction.',
    feedbackC: 'La délation directe peut être perçue comme disproportionnée. Refuser de couvrir est suffisant sans forcément aller plus loin.',
    bonneOption: 'B',
  },
  {
    id: 10,
    situation: 'Vous avez terminé votre tâche avant tout le monde mais il reste encore 2 heures de travail.',
    optionA: 'Vous naviguez sur les réseaux sociaux discrètement.',
    feedbackA: 'En stage, montrer que vous ne savez pas vous occuper est une mauvaise impression. Les réseaux sociaux sur les heures de travail sont risqués.',
    optionB: 'Vous signalez à votre responsable que vous êtes disponible et demandez si vous pouvez aider.',
    feedbackB: 'Excellent réflexe. Prendre l\'initiative de s\'occuper de façon productive est très bien perçu en stage.',
    optionC: 'Vous partez plus tôt sans prévenir.',
    feedbackC: 'Partir sans autorisation est une faute professionnelle grave, surtout en stage.',
    bonneOption: 'B',
  },
  {
    id: 11,
    situation: 'Vous êtes témoin d\'un comportement discriminatoire envers un collègue.',
    optionA: 'Vous ne faites rien pour ne pas vous impliquer.',
    feedbackA: 'Le silence face à la discrimination est souvent perçu comme une forme d\'approbation. La loi protège les témoins qui signalent.',
    optionB: 'Vous signalez les faits à votre responsable ou aux RH de façon factuelle et confidentielle.',
    feedbackB: 'Bonne approche. Signaler sans dramatiser et avec des faits précis est la démarche la plus professionnelle.',
    optionC: 'Vous confrontez directement et publiquement l\'auteur.',
    feedbackC: 'Une confrontation publique peut aggraver la situation. Passer par la hiérarchie ou les RH est plus approprié.',
    bonneOption: 'B',
  },
  {
    id: 12,
    situation: 'Votre manager vous fait une critique sur votre travail lors de votre premier bilan.',
    optionA: 'Vous vous défendez et justifiez chaque point soulevé.',
    feedbackA: 'Se défendre systématiquement bloque l\'apprentissage. Le feedback est un cadeau : écoutez d\'abord.',
    optionB: 'Vous écoutez, posez des questions de clarification, et notez les axes d\'amélioration.',
    feedbackB: 'Excellente posture. Accueillir la critique avec ouverture est une compétence professionnelle très valorisée.',
    optionC: 'Vous acquiescez sans vraiment écouter pour que la conversation se termine vite.',
    feedbackC: 'Faussement acquiescer vous prive des informations utiles pour progresser. Prenez le temps d\'écouter vraiment.',
    bonneOption: 'B',
  },
  {
    id: 13,
    situation: 'On vous donne accès à des informations confidentielles de l\'entreprise.',
    optionA: 'Vous en parlez à vos amis car c\'est une info intéressante.',
    feedbackA: 'C\'est une violation grave de la confidentialité. Même sans intention malveillante, cela peut avoir des conséquences légales.',
    optionB: 'Vous traitez ces informations avec discrétion et ne les partagez qu\'avec les personnes autorisées.',
    feedbackB: 'Parfait. Le respect de la confidentialité est un pilier fondamental du professionnalisme.',
    optionC: 'Vous les notez sur votre téléphone personnel pour ne pas les oublier.',
    feedbackC: 'Stocker des données sensibles sur un support personnel est risqué sur le plan de la sécurité des données.',
    bonneOption: 'B',
  },
  {
    id: 14,
    situation: 'Votre stage se passe mal et votre tuteur ne vous donne pas de travail.',
    optionA: 'Vous profitez de l\'occasion pour ne rien faire.',
    feedbackA: 'Un stage sans mission est une opportunité manquée. C\'est aussi un signal qu\'il faut corriger activement.',
    optionB: 'Vous prenez l\'initiative de proposer votre aide sur des projets et d\'en parler avec votre tuteur pédagogique.',
    feedbackB: 'Bonne réaction. Être proactif dans un stage difficile montre de la maturité. Informer votre école est aussi utile.',
    optionC: 'Vous abandonnez le stage.',
    feedbackC: 'Partir sans en référer à l\'école peut avoir des conséquences académiques. Signalez la situation d\'abord.',
    bonneOption: 'B',
  },
  {
    id: 15,
    situation: 'On vous demande une tâche urgente alors que vous gérez déjà 3 priorités.',
    optionA: 'Vous dites oui sans réfléchir pour faire plaisir.',
    feedbackA: 'Surcharger son planning sans signaler le risque peut conduire à un travail bâclé sur toutes les tâches.',
    optionB: 'Vous expliquez votre charge actuelle et demandez à arbitrer les priorités avec votre responsable.',
    feedbackB: 'Très professionnel. Gérer ses priorités de façon transparente évite les malentendus et montre de l\'organisation.',
    optionC: 'Vous faites l\'urgente et abandonnez les autres sans prévenir.',
    feedbackC: 'Abandonner des tâches sans informer les parties concernées crée de la confusion et de la frustration.',
    bonneOption: 'B',
  },
  {
    id: 16,
    situation: 'Lors d\'un repas d\'équipe, la conversation dévie vers des sujets politiques controversés.',
    optionA: 'Vous défendez avec passion votre opinion.',
    feedbackA: 'En contexte professionnel, afficher des positions politiques marquées peut nuire à votre image ou créer des tensions.',
    optionB: 'Vous restez neutre, écoutez, et redirigez la conversation si besoin.',
    feedbackB: 'Bonne posture. La neutralité en milieu professionnel protège les relations de travail.',
    optionC: 'Vous quittez le repas pour éviter le sujet.',
    feedbackC: 'Partir abruptement est disproportionné. Rester neutre est généralement suffisant.',
    bonneOption: 'B',
  },
  {
    id: 17,
    situation: 'Vous constatez qu\'un process interne est inefficace et prend beaucoup de temps.',
    optionA: 'Vous le faites remarquer lors de la première réunion en présence de tous.',
    feedbackA: 'Critiquer un process en public sans avoir de solution peut être mal perçu, surtout pour un stagiaire.',
    optionB: 'Vous préparez une analyse et proposez une amélioration à votre responsable en tête-à-tête.',
    feedbackB: 'Très bien. Proposer des améliorations de façon constructive et via les bons canaux est valorisé.',
    optionC: 'Vous l\'appliquez sans rien dire.',
    feedbackC: 'Vous passez à côté d\'une opportunité de montrer votre valeur ajoutée.',
    bonneOption: 'B',
  },
  {
    id: 18,
    situation: 'Vous devez faire une présentation orale et vous avez un trac intense.',
    optionA: 'Vous lisez vos notes mot pour mot sans lever les yeux.',
    feedbackA: 'Lire ses notes coupe le contact avec l\'audience et donne une impression de préparation insuffisante.',
    optionB: 'Vous préparez des points clés, vous entraînez, et respirez profondément avant de commencer.',
    feedbackB: 'Bonne stratégie. La préparation réduit le trac et les exercices de respiration aident à se calmer.',
    optionC: 'Vous demandez à quelqu\'un d\'autre de faire la présentation à votre place.',
    feedbackC: 'Éviter systématiquement l\'expression orale ne vous aidera pas à progresser sur cette compétence clé.',
    bonneOption: 'B',
  },
  {
    id: 19,
    situation: 'Un client vous propose un cadeau personnel (bon de réduction, invitation, etc.).',
    optionA: 'Vous acceptez sans hésiter, c\'est sympa.',
    feedbackA: 'Accepter des cadeaux peut créer un conflit d\'intérêts et être problématique selon les politiques de l\'entreprise.',
    optionB: 'Vous déclinez poliment et vérifiez la politique de votre entreprise sur les cadeaux clients.',
    feedbackB: 'Bonne réflexe. Beaucoup d\'entreprises ont des règles précises sur les cadeaux. Mieux vaut vérifier.',
    optionC: 'Vous acceptez mais n\'en parlez à personne.',
    feedbackC: 'Cacher un cadeau reçu peut être encore plus problématique. La transparence est toujours préférable.',
    bonneOption: 'B',
  },
  {
    id: 20,
    situation: 'Vous trouvez une erreur dans les chiffres d\'un rapport avant une présentation importante.',
    optionA: 'Vous signalez l\'erreur immédiatement à la personne responsable.',
    feedbackA: 'Parfait. Signaler une erreur avant qu\'elle ne soit présentée évite une embarrassante correction en public.',
    optionB: 'Vous attendez après la présentation pour ne pas stresser les autres.',
    feedbackB: 'Trop risqué. Si l\'erreur est remarquée pendant la présentation, les dommages sont bien plus importants.',
    optionC: 'Vous la corrigez vous-même sans en parler.',
    feedbackC: 'Modifier un document sans en informer le responsable peut créer de la confusion sur la version officielle.',
    bonneOption: 'A',
  },
  {
    id: 21,
    situation: 'On vous demande de gérer les réseaux sociaux professionnels de l\'entreprise.',
    optionA: 'Vous publiez ce que vous trouvez intéressant, sans validation.',
    feedbackA: 'Publier sans validation peut nuire à l\'image de l\'entreprise. Toute communication officielle doit être approuvée.',
    optionB: 'Vous proposez un planning éditorial et validez chaque post avec votre responsable avant publication.',
    feedbackB: 'Très professionnel. La communication d\'entreprise nécessite une validation pour protéger l\'image de marque.',
    optionC: 'Vous refusez, car vous n\'avez pas appris ça à l\'école.',
    feedbackC: 'Refuser une mission de peur de ne pas savoir faire est une occasion manquée d\'apprendre. Il vaut mieux demander de l\'aide.',
    bonneOption: 'B',
  },
  {
    id: 22,
    situation: 'Votre tuteur de stage parte en vacances 2 semaines et ne vous présente personne.',
    optionA: 'Vous en profitez pour ne pas travailler.',
    feedbackA: 'Un stage est une mission, pas des vacances. L\'absence du tuteur ne justifie pas l\'inaction.',
    optionB: 'Vous identifiez un autre référent disponible et continuez vos missions en documentant votre avancement.',
    feedbackB: 'Excellent. Faire preuve d\'autonomie et d\'organisation en l\'absence du tuteur montre votre sérieux.',
    optionC: 'Vous contactez votre école pour demander de changer de stage.',
    feedbackC: 'Réagir de façon aussi radicale sur 2 semaines est disproportionné. Tentez d\'abord de vous organiser.',
    bonneOption: 'B',
  },
  {
    id: 23,
    situation: 'On vous demande d\'être présent à une réunion dont vous ne connaissez pas l\'ordre du jour.',
    optionA: 'Vous arrivez sans préparation.',
    feedbackA: 'Vous risquez d\'être pris de court si on vous demande votre avis. Mieux vaut anticiper.',
    optionB: 'Vous demandez l\'ordre du jour à l\'avance et préparez quelques points si votre contribution est attendue.',
    feedbackB: 'Bonne démarche. Préparer une réunion montre du sérieux et vous permet d\'y contribuer utilement.',
    optionC: 'Vous déclinez la réunion car vous ne voyez pas son utilité.',
    feedbackC: 'Décliner une réunion à laquelle vous êtes invité peut être mal perçu. Mieux vaut y aller préparé.',
    bonneOption: 'B',
  },
  {
    id: 24,
    situation: 'Vous découvrez que votre entreprise ne respecte pas une réglementation environnementale.',
    optionA: 'Vous publiez l\'information sur vos réseaux personnels.',
    feedbackA: 'Agir ainsi peut avoir des conséquences légales pour vous (violation de confidentialité) et ne résout pas le problème.',
    optionB: 'Vous en informez votre tuteur ou la personne habilitée en interne, et documentez les faits.',
    feedbackB: 'Bonne démarche. Les canaux internes sont le premier recours. Des dispositifs légaux existent si rien n\'est fait.',
    optionC: 'Vous n\'en parlez à personne et faites comme si vous n\'aviez rien vu.',
    feedbackC: 'Ignorer une non-conformité réglementaire peut vous rendre complice si la situation empire.',
    bonneOption: 'B',
  },
  {
    id: 25,
    situation: 'Un stagiaire d\'une autre équipe se plaint de son maître de stage et vous demande de l\'aider.',
    optionA: 'Vous lui donnez les coordonnées RH de l\'entreprise et l\'encouragez à formaliser sa demande.',
    feedbackA: 'Bonne aide. Orienter vers les bons interlocuteurs est la meilleure façon de l\'aider sans vous substituer à lui.',
    optionB: 'Vous intervenez directement auprès du maître de stage de votre collègue.',
    feedbackB: 'Intervenir dans une relation qui n\'est pas la vôtre peut créer des conflits supplémentaires.',
    optionC: 'Vous ne faites rien pour ne pas vous mêler des affaires des autres.',
    feedbackC: 'Ne rien faire n\'aide pas. Vous pouvez orienter sans vous impliquer directement dans le conflit.',
    bonneOption: 'A',
  },
  {
    id: 26,
    situation: 'Lors de votre entretien de bilan mi-stage, on vous demande ce que vous pensez de votre équipe.',
    optionA: 'Vous critiquez ouvertement les collègues qui vous ont déçu.',
    feedbackA: 'Critiquer nommément des collègues lors d\'un bilan peut créer des tensions et nuire à votre image.',
    optionB: 'Vous partagez des observations constructives en vous concentrant sur les faits, pas les personnes.',
    feedbackB: 'Excellent. Donner un feedback factuel et constructif est une compétence professionnelle précieuse.',
    optionC: 'Vous dites que tout va parfaitement bien même si ce n\'est pas le cas.',
    feedbackC: 'Une vision uniquement positive prive l\'entreprise de retours utiles et peut paraître peu crédible.',
    bonneOption: 'B',
  },
  {
    id: 27,
    situation: 'On vous confie un projet créatif mais votre idée est différente de ce qu\'attend le client.',
    optionA: 'Vous imposez votre vision car elle est meilleure.',
    feedbackA: 'En entreprise, la commande du client prime. Votre rôle est de servir ses besoins, pas d\'imposer vos préférences.',
    optionB: 'Vous présentez votre idée en parallèle de la version attendue, en expliquant la valeur ajoutée.',
    feedbackB: 'Très bien. Proposer sans imposer laisse le choix au client tout en montrant votre créativité.',
    optionC: 'Vous produisez exactement ce qui a été demandé sans proposer d\'alternative.',
    feedbackC: 'Correct, mais une proposition alternative bien argumentée peut valoriser votre contribution.',
    bonneOption: 'B',
  },
  {
    id: 28,
    situation: 'Vous avez une réunion à 9h et vous vous réveillez à 8h45.',
    optionA: 'Vous prévenez immédiatement que vous serez en retard et estimez l\'heure d\'arrivée.',
    feedbackA: 'Parfait. Prévenir en amont est la réaction la plus professionnelle face à un retard inévitable.',
    optionB: 'Vous arrivez en retard sans prévenir personne.',
    feedbackB: 'Arriver en retard sans prévenir perturbe l\'organisation et envoie un signal négatif sur votre fiabilité.',
    optionC: 'Vous n\'y allez pas et prétextez une maladie soudaine.',
    feedbackC: 'Mentir sur votre absence est une faute grave. Mieux vaut assumer le retard et vous excuser.',
    bonneOption: 'A',
  },
  {
    id: 29,
    situation: 'On vous demande de faire une analyse de marché mais vous ne savez pas par où commencer.',
    optionA: 'Vous rendez un document incomplet sans demander d\'aide.',
    feedbackA: 'Rendre un travail incomplet sans avoir demandé de l\'aide est une occasion manquée et une déception pour votre tuteur.',
    optionB: 'Vous cherchez des méthodes en ligne, commencez une trame et posez des questions ciblées à votre responsable.',
    feedbackB: 'Excellente approche. Montrer que vous avez cherché avant de demander est très valorisé.',
    optionC: 'Vous demandez à ChatGPT de tout faire et rendez le résultat tel quel.',
    feedbackC: 'Utiliser l\'IA comme point de départ peut être utile, mais sans vérification ni adaptation, cela nuit à votre apprentissage et peut contenir des erreurs.',
    bonneOption: 'B',
  },
  {
    id: 30,
    situation: 'Votre stage se termine et vous voulez maintenir le contact avec l\'équipe.',
    optionA: 'Vous ajoutez tout le monde sur les réseaux sociaux personnels.',
    feedbackA: 'Mélanger sphère professionnelle et personnelle sans discernement peut être mal perçu.',
    optionB: 'Vous envoyez un email de remerciement personnalisé et connectez avec les personnes pertinentes sur LinkedIn.',
    feedbackB: 'Parfait. Un remerciement sincère et une connexion LinkedIn entretiennent votre réseau de façon professionnelle.',
    optionC: 'Vous partez sans rien dire car vous pensez que ce n\'est pas important.',
    feedbackC: 'Ne pas saluer votre départ est une occasion manquée de marquer les esprits positivement.',
    bonneOption: 'B',
  },
  {
    id: 31,
    situation: 'Votre responsable vous demande votre avis sur sa présentation juste avant qu\'il la soumette.',
    optionA: 'Vous lui dites que c\'est parfait pour ne pas le stresser.',
    feedbackA: 'Un faux retour positif peut conduire à une présentation de mauvaise qualité. On vous demande votre avis pour être honnête.',
    optionB: 'Vous donnez un retour honnête et constructif, en soulignant ce qui fonctionne et ce qui pourrait être amélioré.',
    feedbackB: 'Très bien. Savoir formuler un feedback honnête et bienveillant est une compétence rare et précieuse.',
    optionC: 'Vous dites que vous n\'avez pas eu le temps de regarder.',
    feedbackC: 'Si on vous demande un avis et que vous déclinez, cela peut être perçu comme un désintérêt.',
    bonneOption: 'B',
  },
  {
    id: 32,
    situation: 'Vous êtes invité à un afterwork d\'équipe mais vous ne buvez pas d\'alcool.',
    optionA: 'Vous refusez l\'invitation pour éviter la pression sociale.',
    feedbackA: 'Refuser systématiquement les moments informels peut vous exclure de la dynamique d\'équipe.',
    optionB: 'Vous participez avec plaisir et commandez une boisson sans alcool, sans vous justifier longuement.',
    feedbackB: 'Parfait. Participer aux moments d\'équipe est important, et ne pas boire d\'alcool est totalement normal.',
    optionC: 'Vous consommez de l\'alcool pour ne pas faire différent des autres.',
    feedbackC: 'Vous n\'avez jamais à consommer de l\'alcool contre votre gré. Votre confort passe avant la conformité sociale.',
    bonneOption: 'B',
  },
  {
    id: 33,
    situation: 'Votre ordinateur professionnel tombe en panne au milieu d\'une mission urgente.',
    optionA: 'Vous attendez qu\'on vienne vous voir pour signaler le problème.',
    feedbackA: 'Attendre passivement rallonge inutilement le délai de résolution et peut faire douter de votre réactivité.',
    optionB: 'Vous prévenez immédiatement votre responsable et le service informatique, et proposez des solutions alternatives.',
    feedbackB: 'Excellente réaction. Signaler et proposer des alternatives montre votre professionnalisme.',
    optionC: 'Vous utilisez votre ordinateur personnel pour continuer à travailler sur des données internes.',
    feedbackC: 'Utiliser un équipement personnel pour des données professionnelles peut poser des problèmes de sécurité et de conformité.',
    bonneOption: 'B',
  },
  {
    id: 34,
    situation: 'Un client demande une remise non autorisée et menace de partir chez la concurrence.',
    optionA: 'Vous accordez la remise pour garder le client.',
    feedbackA: 'Accorder une remise sans autorisation dépasse vos compétences et peut créer un précédent problématique.',
    optionB: 'Vous expliquez ce que vous pouvez faire, transmettez la demande à votre responsable et maintenez la relation.',
    feedbackB: 'Parfait. Escalader vers la bonne personne tout en maintenant la relation client est la bonne démarche.',
    optionC: 'Vous refusez sèchement sans explication.',
    feedbackC: 'Un refus sans explication ni solution de rechange risque de perdre le client et de nuire à votre image.',
    bonneOption: 'B',
  },
  {
    id: 35,
    situation: 'On vous demande d\'appeler des clients pour une enquête de satisfaction.',
    optionA: 'Vous inventez des réponses pour remplir les tableaux plus vite.',
    feedbackA: 'Falsifier des données est une faute grave. Les décisions stratégiques de l\'entreprise reposent sur ces données.',
    optionB: 'Vous appelez réellement les clients, notez fidèlement leurs réponses et signalez les difficultés rencontrées.',
    feedbackB: 'Très bien. L\'honnêteté dans la collecte de données est essentielle à la qualité des décisions de l\'entreprise.',
    optionC: 'Vous faites appel à des scripts générés par IA pour les commentaires.',
    feedbackC: 'Remplir des enquêtes de satisfaction avec des données fictives, même générées par IA, est une falsification.',
    bonneOption: 'B',
  },
  {
    id: 36,
    situation: 'On vous affecte à un projet pour lequel vous n\'avez reçu aucune formation.',
    optionA: 'Vous dites que ce n\'est pas votre rôle et que vous n\'avez pas été formé.',
    feedbackA: 'En entreprise, les projets sont souvent formateurs. Refuser de s\'engager sans essayer est peu valorisé.',
    optionB: 'Vous identifiez les compétences manquantes, cherchez des ressources et demandez un accompagnement.',
    feedbackB: 'Bonne attitude. Prendre l\'initiative d\'apprendre montre de l\'autonomie et de l\'engagement.',
    optionC: 'Vous faites de votre mieux sans informer personne de vos lacunes.',
    feedbackC: 'Travailler en silence sur un sujet mal maîtrisé peut produire des erreurs coûteuses. Mieux vaut signaler et demander de l\'aide.',
    bonneOption: 'B',
  },
  {
    id: 37,
    situation: 'Votre stage se déroule dans une ville différente de votre domicile et vous vous sentez isolé.',
    optionA: 'Vous restez dans votre chambre et évitez toute interaction sociale.',
    feedbackA: 'L\'isolement peut affecter votre motivation et votre performance. Il est important de créer des liens, même professionnels.',
    optionB: 'Vous cherchez à participer aux activités de l\'équipe et explorez la ville pour vous sentir mieux.',
    feedbackB: 'Bonne approche. Construire des liens locaux, même temporaires, améliore votre bien-être et votre intégration.',
    optionC: 'Vous rentrez chaque week-end et n\'investissez pas dans votre intégration locale.',
    feedbackC: 'Rentrer régulièrement peut vous empêcher de vous intégrer et peut peser sur votre énergie de la semaine.',
    bonneOption: 'B',
  },
  {
    id: 38,
    situation: 'Votre maître de stage vous demande de travailler pendant vos heures de pause.',
    optionA: 'Vous acceptez toujours, sans jamais poser de limite.',
    feedbackA: 'Accepter systématiquement dépasse le cadre légal et peut mener à l\'épuisement. Vous avez des droits.',
    optionB: 'Vous vérifiez votre convention de stage et en discutez calmement avec votre tuteur si besoin.',
    feedbackB: 'Bonne réaction. La convention de stage définit vos horaires. Une discussion ouverte est toujours préférable.',
    optionC: 'Vous refusez systématiquement toute heure supplémentaire sans discussion.',
    feedbackC: 'Un refus systématique sans discussion peut créer de la tension inutile. Parlez-en d\'abord avec votre tuteur.',
    bonneOption: 'B',
  },
  {
    id: 39,
    situation: 'Votre maître de stage vous critique devant toute l\'équipe d\'une façon blessante.',
    optionA: 'Vous vous défendez immédiatement et vigoureusement.',
    feedbackA: 'Une réaction vive en public peut aggraver la situation. Il vaut mieux absorber le choc et réagir en privé.',
    optionB: 'Vous restez calme sur le moment, puis demandez un entretien en privé pour discuter de la façon dont le feedback a été formulé.',
    feedbackB: 'Très professionnel. Réagir avec maturité face à une critique blessante et en parler en privé est la meilleure approche.',
    optionC: 'Vous ne dites rien et n\'y revenez jamais, même si cela se reproduit.',
    feedbackC: 'Ne pas réagir du tout peut normaliser un comportement irrespectueux. Il est utile d\'en parler, au moins en privé.',
    bonneOption: 'B',
  },
  {
    id: 40,
    situation: 'On vous demande de choisir entre deux outils digitaux pour un projet et vous ne connaissez aucun des deux.',
    optionA: 'Vous choisissez au hasard.',
    feedbackA: 'Un choix aléatoire sans analyse peut conduire à utiliser un outil inadapté, perdant du temps et des ressources.',
    optionB: 'Vous les testez rapidement, listez les avantages et inconvénients de chacun et présentez votre recommandation.',
    feedbackB: 'Excellent. Proposer une analyse comparative même brève montre du sérieux et de la méthode.',
    optionC: 'Vous demandez à votre responsable de choisir à votre place.',
    feedbackC: 'On vous a confié la décision parce qu\'on vous fait confiance. Faire l\'effort d\'analyser vous-même valorise votre contribution.',
    bonneOption: 'B',
  },
  {
    id: 41,
    situation: 'Votre convention de stage prévoit une gratification, mais vous ne l\'avez pas reçue depuis 2 mois.',
    optionA: 'Vous n\'en parlez pas pour ne pas créer de tensions.',
    feedbackA: 'La gratification de stage est un droit légal. Ne pas la réclamer n\'est pas dans votre intérêt.',
    optionB: 'Vous contactez poliment les RH ou votre tuteur pour signaler le retard et demander une régularisation.',
    feedbackB: 'Parfait. Réclamer ce qui vous est dû de façon professionnelle et par écrit est tout à fait légitime.',
    optionC: 'Vous menacez de partir si vous ne recevez pas votre gratification aujourd\'hui.',
    feedbackC: 'Un ultimatum d\'emblée est disproportionné. Un rappel poli et documenté est plus efficace.',
    bonneOption: 'B',
  },
  {
    id: 42,
    situation: 'Vous remarquez que votre collègue utilise des ressources de l\'entreprise à des fins personnelles.',
    optionA: 'Vous le signalez immédiatement à la direction.',
    feedbackA: 'Avant de signaler à la direction, il peut être utile d\'évaluer la gravité des faits et d\'en parler à votre tuteur.',
    optionB: 'Vous évaluez la gravité, en parlez si nécessaire à votre tuteur, et signalez si c\'est manifeste.',
    feedbackB: 'Bonne approche proportionnée. Tous les abus ne méritent pas la même réponse, mais les ignorer n\'est pas la solution.',
    optionC: 'Vous l\'imitez car "tout le monde le fait".',
    feedbackC: 'Se justifier par "tout le monde le fait" n\'est pas une défense valide. Vous restez responsable de vos actes.',
    bonneOption: 'B',
  },
  {
    id: 43,
    situation: 'Lors de votre entretien de fin de stage, on vous demande si vous seriez intéressé par un CDI.',
    optionA: 'Vous dites non sans explication, même si vous êtes intéressé.',
    feedbackA: 'Un non non expliqué ferme une porte. Si c\'est par timing, dites-le : "Pas maintenant, mais je suis intéressé à terme."',
    optionB: 'Vous exprimez honnêtement votre intérêt ou non, et expliquez votre situation.',
    feedbackB: 'La transparence est toujours préférable. Un recruteur apprécie une réponse honnête, même si elle n\'est pas celle attendue.',
    optionC: 'Vous dites oui enthousiaste même si vous ne le pensez pas.',
    feedbackC: 'Faussement vous engager peut mener à des situations inconfortables si l\'offre est formalisée.',
    bonneOption: 'B',
  },
  {
    id: 44,
    situation: 'Vous avez été félicité pour un travail, mais une autre personne a aussi contribué.',
    optionA: 'Vous acceptez les félicitations sans mentionner votre collègue.',
    feedbackA: 'S\'attribuer seul un travail collectif peut nuire à la confiance au sein de l\'équipe.',
    optionB: 'Vous remerciez et mentionnez spontanément la contribution de votre collègue.',
    feedbackB: 'Parfait. Valoriser les autres renforce votre crédibilité et crée un bon esprit d\'équipe.',
    optionC: 'Vous redirigez les compliments uniquement vers votre collègue.',
    feedbackC: 'Sous-estimer votre propre contribution n\'est pas nécessaire. Reconnaître les deux est la bonne approche.',
    bonneOption: 'B',
  },
  {
    id: 45,
    situation: 'On vous donne accès aux réseaux sociaux de l\'entreprise pour animer une story.',
    optionA: 'Vous publiez directement votre idée sans validation.',
    feedbackA: 'Toute communication officielle de l\'entreprise doit être validée avant publication.',
    optionB: 'Vous créez un storyboard, le soumettez à validation, puis publiez après accord.',
    feedbackB: 'Très professionnel. Le process de validation protège l\'image de l\'entreprise et vous protège vous aussi.',
    optionC: 'Vous refusez cette mission car vous ne vous sentez pas légitime.',
    feedbackC: 'Refuser une opportunité par manque de confiance vous prive d\'expérience. Demandez des consignes claires et lancez-vous.',
    bonneOption: 'B',
  },
  {
    id: 46,
    situation: 'Votre responsable vous assigne une tâche que vous avez déjà faite la semaine dernière.',
    optionA: 'Vous la refaites sans rien dire.',
    feedbackA: 'Répéter en silence une tâche déjà effectuée est une perte de temps. Signalez-le avec diplomatie.',
    optionB: 'Vous signalez poliment que vous avez déjà réalisé cette tâche et proposez de partager le résultat existant.',
    feedbackB: 'Très bien. Éviter les doublons en informant votre responsable est utile pour tous.',
    optionC: 'Vous lui dites qu\'il se répète et que c\'est une perte de temps.',
    feedbackC: 'Même si vous avez raison, le ton compte. Une formulation respectueuse est plus efficace qu\'une critique directe.',
    bonneOption: 'B',
  },
  {
    id: 47,
    situation: 'Vous êtes invité à exprimer vos idées lors d\'une session de brainstorming.',
    optionA: 'Vous ne dites rien car vous pensez que vos idées ne sont pas assez bonnes.',
    feedbackA: 'En brainstorming, toutes les idées ont de la valeur. Retenir ses idées par manque de confiance est une occasion manquée.',
    optionB: 'Vous partagez vos idées en les formulant clairement, même imparfaitement.',
    feedbackB: 'Parfait. Participer montre votre engagement et votre créativité, même si toutes les idées ne seront pas retenues.',
    optionC: 'Vous répétez les idées des autres en les reformulant comme si elles étaient les vôtres.',
    feedbackC: 'Réutiliser les idées des autres sans les citer peut nuire à votre crédibilité.',
    bonneOption: 'B',
  },
  {
    id: 48,
    situation: 'On vous demande de rédiger un email important à un client en anglais.',
    optionA: 'Vous rédigez directement et envoyez sans relecture.',
    feedbackA: 'Un email professionnel en langue étrangère doit être relu attentivement, surtout pour une communication cliente.',
    optionB: 'Vous rédigez le mieux possible, utilisez des outils de correction et faites valider si nécessaire.',
    feedbackB: 'Excellent. Utiliser des outils pour améliorer votre production et la faire valider est une bonne pratique.',
    optionC: 'Vous demandez à quelqu\'un d\'autre de le rédiger à votre place.',
    feedbackC: 'Si on vous confie la tâche, faites l\'effort vous-même. Demandez de l\'aide si nécessaire, mais ne déléguez pas entièrement.',
    bonneOption: 'B',
  },
  {
    id: 49,
    situation: 'Votre manager critique une erreur que vous avez commise par email, avec toute l\'équipe en copie.',
    optionA: 'Vous répondez à tous pour vous défendre.',
    feedbackA: 'Répondre à tous en se défendant amplifie le problème et peut nuire à votre image.',
    optionB: 'Vous reconnaissez l\'erreur en privé, proposez une correction et exprimez calmement votre ressenti sur la forme si nécessaire.',
    feedbackB: 'Très mature. Reconnaître l\'erreur et séparer le fond (l\'erreur) de la forme (la communication publique) est professionnel.',
    optionC: 'Vous ignorez l\'email.',
    feedbackC: 'Ignorer un email de votre manager peut être perçu comme un manque de respect et aggraver la situation.',
    bonneOption: 'B',
  },
  {
    id: 50,
    situation: 'Votre dernier jour de stage arrive et vous n\'avez pas encore récupéré votre attestation de stage.',
    optionA: 'Vous partez sans rien demander en vous disant qu\'on vous l\'enverra.',
    feedbackA: 'Partir sans votre attestation peut compliquer vos démarches académiques. Mieux vaut la demander avant de partir.',
    optionB: 'Vous relancez poliment les RH ou votre tuteur pour obtenir le document avant votre départ.',
    feedbackB: 'Parfait. Demander vos documents administratifs avant votre départ est indispensable pour votre dossier.',
    optionC: 'Vous ne la réclamez pas car vous pensez que ce n\'est pas important.',
    feedbackC: 'L\'attestation de stage est souvent requise par votre école. Ne pas la réclamer peut avoir des conséquences pour votre validation.',
    bonneOption: 'B',
  },
]

export interface QuestionEntretien {
  id: number
  question: string
  categorie: 'motivations' | 'parcours' | 'competences' | 'comportementales' | 'salaire'
  conseilReponse: string
  aEviter: string
  bonneAmorce: string
}

export const questionsEntretien: QuestionEntretien[] = [
  {
    id: 1,
    question: 'Pourquoi avez-vous choisi ce secteur d\'activité ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez une connaissance réelle du secteur et liez-la à votre parcours ou à une expérience personnelle.',
    aEviter: '"Parce que ça paye bien" ou une réponse générique sans lien avec votre profil.',
    bonneAmorce: '"Ce qui m\'a attiré vers ce secteur, c\'est avant tout… [expérience ou observation concrète]."',
  },
  {
    id: 2,
    question: 'Pourquoi voulez-vous travailler dans notre entreprise ?',
    categorie: 'motivations',
    conseilReponse: 'Citez des éléments précis sur l\'entreprise (projets, valeurs, actualité) que vous avez vraiment recherchés.',
    aEviter: '"C\'est une grande entreprise connue" ou "c\'est proche de chez moi".',
    bonneAmorce: '"J\'ai été particulièrement intéressé par [projet / valeur / actualité de l\'entreprise]…"',
  },
  {
    id: 3,
    question: 'Où vous voyez-vous dans 5 ans ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez de l\'ambition et une direction claire, sans promettre de rester à vie ni paraître indécis.',
    aEviter: '"Je ne sais pas encore" ou un projet totalement hors sujet (reconversion, création perso).',
    bonneAmorce: '"Dans 5 ans, j\'aimerais avoir développé des compétences en [domaine] et prendre plus de responsabilités dans…"',
  },
  {
    id: 4,
    question: 'Qu\'est-ce qui vous motive le plus dans un poste ?',
    categorie: 'motivations',
    conseilReponse: 'Soyez spécifique : autonomie, impact, apprentissage, contact humain. Reliez à des exemples vécus.',
    aEviter: '"Le salaire" ou une longue liste floue sans hiérarchie.',
    bonneAmorce: '"Ce qui me motive vraiment, c\'est [motivation principale], comme lorsque j\'ai eu l\'occasion de…"',
  },
  {
    id: 5,
    question: 'Pourquoi avez-vous choisi cette formation ?',
    categorie: 'motivations',
    conseilReponse: 'Expliquez votre parcours de façon logique et cohérente. Mettez en avant ce que la formation vous a apporté.',
    aEviter: '"Par défaut" ou parce que c\'était la formation la plus accessible.',
    bonneAmorce: '"J\'ai choisi cette formation car elle correspondait à mon projet de… et me permettait de développer…"',
  },
  {
    id: 6,
    question: 'Parlez-moi de votre parcours en quelques minutes.',
    categorie: 'parcours',
    conseilReponse: 'Structurez votre réponse : formation, expériences clés, compétences acquises, et où vous en êtes. Restez sous 3 minutes.',
    aEviter: 'Réciter votre CV mot pour mot ou partir dans un récit très long et peu structuré.',
    bonneAmorce: '"En quelques mots, je suis actuellement en [formation] et j\'ai eu l\'occasion de… ce qui m\'a amené à…"',
  },
  {
    id: 7,
    question: 'Quelle a été votre première expérience professionnelle marquante ?',
    categorie: 'parcours',
    conseilReponse: 'Racontez une expérience concrète avec un début, un défi et un apprentissage. La méthode STAR est idéale.',
    aEviter: 'Choisir une expérience banale ou en parler de façon trop vague.',
    bonneAmorce: '"Lors de mon expérience chez [X], j\'ai dû faire face à [situation] et voici ce que j\'ai appris…"',
  },
  {
    id: 8,
    question: 'Avez-vous des expériences de travail en équipe ?',
    categorie: 'parcours',
    conseilReponse: 'Donnez un exemple concret, expliquez votre rôle dans l\'équipe et le résultat obtenu.',
    aEviter: '"Oui, souvent" sans donner de détails ou d\'exemple précis.',
    bonneAmorce: '"Oui, lors de [projet], nous étions [nombre] et mon rôle était de… Ce qui a permis de…"',
  },
  {
    id: 9,
    question: 'Quels sont vos centres d\'intérêt en dehors du travail ?',
    categorie: 'parcours',
    conseilReponse: 'Choisissez des activités qui reflètent des qualités transférables : leadership, créativité, discipline, etc.',
    aEviter: '"Regarder des séries" ou ne pas savoir quoi répondre.',
    bonneAmorce: '"En dehors du travail, je pratique [activité] qui m\'apprend [compétence] applicable aussi en entreprise."',
  },
  {
    id: 10,
    question: 'Avez-vous des expériences à l\'international ?',
    categorie: 'parcours',
    conseilReponse: 'Valorisez toute expérience : voyage, échange, langue parlée, projets avec des équipes internationales.',
    aEviter: 'Dire non sèchement. Même une courte expérience peut être valorisée.',
    bonneAmorce: '"J\'ai eu l\'occasion de [voyager / travailler avec / étudier à] [lieu], ce qui m\'a permis de…"',
  },
  {
    id: 11,
    question: 'Quelles sont vos principales compétences ?',
    categorie: 'competences',
    conseilReponse: 'Citez 3 compétences max, illustrées par des exemples concrets. Adaptez-les au poste visé.',
    aEviter: 'Lister 10 compétences sans illustration ni lien avec le poste.',
    bonneAmorce: '"Je dirais que mes points forts sont [compétence 1], [compétence 2]… ce que j\'ai pu démontrer lors de…"',
  },
  {
    id: 12,
    question: 'Parlez-moi d\'une réussite dont vous êtes fier(e).',
    categorie: 'competences',
    conseilReponse: 'Utilisez la méthode STAR : Situation, Tâche, Action, Résultat. Montrez votre apport personnel.',
    aEviter: 'Choisir une réussite collective sans mettre en valeur votre rôle propre.',
    bonneAmorce: '"Un moment dont je suis fier(e) est lorsque j\'ai [action] ce qui a permis [résultat chiffré ou concret]…"',
  },
  {
    id: 13,
    question: 'Comment gérez-vous le stress ?',
    categorie: 'competences',
    conseilReponse: 'Reconnaissez que le stress peut exister, puis décrivez une technique concrète que vous utilisez.',
    aEviter: '"Je ne stresse jamais" — peu crédible — ou une réponse générique sans exemple.',
    bonneAmorce: '"Dans une situation stressante comme [exemple], ce qui m\'aide c\'est de [technique]…"',
  },
  {
    id: 14,
    question: 'Quelles sont vos compétences numériques ?',
    categorie: 'competences',
    conseilReponse: 'Citez des outils maîtrisés (Excel, CRM, outils de gestion, IA…) en précisant votre niveau réel.',
    aEviter: '"Je maîtrise tous les outils" sans précision, ou mentir sur votre niveau.',
    bonneAmorce: '"Je suis à l\'aise avec [outil] que j\'utilise pour [usage], et j\'apprends actuellement…"',
  },
  {
    id: 15,
    question: 'Êtes-vous à l\'aise avec les chiffres et l\'analyse de données ?',
    categorie: 'competences',
    conseilReponse: 'Soyez honnête sur votre niveau et donnez un exemple concret si vous êtes à l\'aise.',
    aEviter: '"Pas vraiment" sans montrer d\'envie d\'apprendre, ou surestimer vos compétences.',
    bonneAmorce: '"J\'ai déjà travaillé sur [type de données] avec [outil], ce qui m\'a permis de [résultat]…"',
  },
  {
    id: 16,
    question: 'Décrivez une situation où vous avez dû gérer un conflit.',
    categorie: 'comportementales',
    conseilReponse: 'Racontez un conflit réel, expliquez comment vous avez cherché une solution, et mentionnez le résultat.',
    aEviter: '"Je n\'ai jamais eu de conflits" — improbable — ou une situation où vous avez perdu votre calme.',
    bonneAmorce: '"Lors de [situation], il y avait une divergence entre [parties]. J\'ai choisi d\'aborder la chose en…"',
  },
  {
    id: 17,
    question: 'Comment réagissez-vous face à un changement inattendu ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous êtes adaptable, sans être opportuniste. Donnez un exemple.',
    aEviter: '"Cela m\'angoisse" sans rien de constructif, ou prétendre être parfaitement zen en toutes circonstances.',
    bonneAmorce: '"Face à un changement inattendu comme [situation], j\'essaie d\'abord de… puis de…"',
  },
  {
    id: 18,
    question: 'Parlez-moi d\'un échec et ce que vous en avez appris.',
    categorie: 'comportementales',
    conseilReponse: 'Choisissez un vrai échec, assumez-le sans excuses, et mettez l\'accent sur l\'apprentissage.',
    aEviter: '"Je n\'en vois pas" ou transformer l\'échec en réussite déguisée dès le départ.',
    bonneAmorce: '"Lors de [situation], j\'ai fait l\'erreur de… Ce que j\'en ai retenu, c\'est que…"',
  },
  {
    id: 19,
    question: 'Êtes-vous plutôt leader ou suiveur ?',
    categorie: 'comportementales',
    conseilReponse: 'Nuancez : vous pouvez être leader dans certains contextes et collaboratif dans d\'autres. Illustrez.',
    aEviter: '"Toujours leader" (peut paraître arrogant) ou "toujours suiveur" (trop passif).',
    bonneAmorce: '"Cela dépend du contexte. Par exemple, lors de [situation], j\'ai pris l\'initiative de… mais je sais aussi m\'adapter quand…"',
  },
  {
    id: 20,
    question: 'Comment prenez-vous des décisions difficiles ?',
    categorie: 'comportementales',
    conseilReponse: 'Décrivez un processus : recueillir les faits, consulter si besoin, peser les conséquences, décider.',
    aEviter: '"Je suis mon instinct" sans aucune méthode, ou l\'inverse, paraître incapable de décider seul.',
    bonneAmorce: '"Quand je dois décider dans un contexte difficile, ma méthode est d\'abord de… puis de…"',
  },
  {
    id: 21,
    question: 'Avez-vous déjà travaillé sous pression de temps ?',
    categorie: 'comportementales',
    conseilReponse: 'Donnez un exemple concret avec les actions mises en place et le résultat.',
    aEviter: '"Oui et ça ne me pose aucun problème" sans exemple.',
    bonneAmorce: '"Lors de [situation], j\'avais [délai] pour [mission]. J\'ai organisé mon travail en… et j\'ai pu…"',
  },
  {
    id: 22,
    question: 'Avez-vous déjà managé ou coordonné un groupe ?',
    categorie: 'comportementales',
    conseilReponse: 'Même sans expérience officielle, valorisez des projets scolaires, associatifs ou sportifs.',
    aEviter: '"Non, jamais" sans proposer d\'expérience proche ou d\'analogie.',
    bonneAmorce: '"Lors de [projet scolaire / associatif], j\'ai pris le rôle de coordinateur et j\'ai dû…"',
  },
  {
    id: 23,
    question: 'Quelles sont vos prétentions salariales ?',
    categorie: 'salaire',
    conseilReponse: 'Renseignez-vous avant l\'entretien sur les fourchettes du secteur et proposez une fourchette cohérente.',
    aEviter: 'Donner un chiffre sans vous être renseigné, ou dire "ce que vous me proposez".',
    bonneAmorce: '"D\'après mes recherches sur le secteur, je situerais mes attentes entre [X] et [Y] euros, selon les responsabilités…"',
  },
  {
    id: 24,
    question: 'La rémunération est-elle votre principale motivation ?',
    categorie: 'salaire',
    conseilReponse: 'Honnêteté et équilibre : le salaire compte, mais ce n\'est pas le seul critère. Mentionnez d\'autres éléments.',
    aEviter: '"Oui, c\'est ma priorité absolue" ou "Non, l\'argent ne m\'intéresse pas" — les deux extrêmes sonnent faux.',
    bonneAmorce: '"La rémunération est un critère parmi d\'autres. Ce qui compte aussi pour moi, c\'est [ambiance / mission / évolution]…"',
  },
  {
    id: 25,
    question: 'Seriez-vous prêt(e) à accepter un salaire inférieur à vos attentes pour ce poste ?',
    categorie: 'salaire',
    conseilReponse: 'Ne dites pas oui d\'emblée. Demandez ce qui justifie l\'écart et montrez que vous vous positionnez selon la valeur apportée.',
    aEviter: '"Oui, bien sûr, je suis flexible sur tout" — cela peut diminuer votre valeur perçue.',
    bonneAmorce: '"Je suis ouvert(e) à la discussion, mais j\'aimerais comprendre ce qui justifie cet écart par rapport au marché…"',
  },
  {
    id: 26,
    question: 'Quels sont vos axes d\'amélioration ?',
    categorie: 'competences',
    conseilReponse: 'Citez un vrai point à améliorer (pas une fausse modestie) et montrez comment vous y travaillez.',
    aEviter: '"Je suis perfectionniste" ou "je travaille trop" — des réponses trop clichées.',
    bonneAmorce: '"Un axe sur lequel je travaille est [faiblesse réelle], j\'essaie de l\'améliorer en…"',
  },
  {
    id: 27,
    question: 'Pourquoi devrions-nous vous choisir plutôt qu\'un autre candidat ?',
    categorie: 'motivations',
    conseilReponse: 'Résumez en 2-3 points clés votre valeur ajoutée spécifique pour CE poste.',
    aEviter: 'Parler de façon générale sans lien avec le poste, ou être trop modeste.',
    bonneAmorce: '"Je pense que ce qui me différencie, c\'est [compétence / expérience / attitude] que j\'ai pu démontrer en…"',
  },
  {
    id: 28,
    question: 'Êtes-vous disponible pour travailler le week-end ou en dehors des horaires standards ?',
    categorie: 'competences',
    conseilReponse: 'Soyez honnête sur votre disponibilité réelle sans vous surengager.',
    aEviter: '"Toujours disponible" si ce n\'est pas vrai, ou un refus catégorique sans nuance.',
    bonneAmorce: '"Je suis prêt(e) à m\'adapter ponctuellement si la situation le nécessite, tout en maintenant un équilibre…"',
  },
  {
    id: 29,
    question: 'Comment organisez-vous votre travail au quotidien ?',
    categorie: 'competences',
    conseilReponse: 'Décrivez une méthode concrète (to-do list, outils de planification, priorisation).',
    aEviter: '"Au fur et à mesure" sans aucune organisation visible.',
    bonneAmorce: '"Au quotidien, je commence par [méthode de priorisation], j\'utilise [outil si applicable] et je…"',
  },
  {
    id: 30,
    question: 'Avez-vous des questions pour nous ?',
    categorie: 'motivations',
    conseilReponse: 'Posez 2-3 questions préparées à l\'avance sur le poste, l\'équipe, les projets ou les perspectives d\'évolution.',
    aEviter: '"Non, c\'est bon" — cela montre un manque d\'intérêt — ou poser des questions sur les congés dès le premier entretien.',
    bonneAmorce: '"Oui, j\'aurais quelques questions : [question sur le poste], [question sur l\'équipe]…"',
  },
  {
    id: 31,
    question: 'Décrivez votre style de communication.',
    categorie: 'comportementales',
    conseilReponse: 'Mentionnez des compétences comme l\'écoute, la clarté, l\'adaptation au contexte. Illustrez avec un exemple.',
    aEviter: '"Je m\'adapte" sans aucun exemple concret.',
    bonneAmorce: '"Je dirais que je suis [direct / à l\'écoute / structuré] dans ma communication. Par exemple, lors de [situation]…"',
  },
  {
    id: 32,
    question: 'Avez-vous déjà dû vous adapter à une nouvelle culture d\'entreprise ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez votre capacité d\'adaptation et d\'observation. Donnez un exemple.',
    aEviter: '"Je n\'ai pas vraiment d\'expérience là-dessus." Valorisez même un changement de milieu scolaire ou associatif.',
    bonneAmorce: '"Lors de mon passage chez [entreprise / école / association], la culture était très différente de ce que je connaissais. J\'ai dû…"',
  },
  {
    id: 33,
    question: 'Quelle est votre relation au travail en autonomie ?',
    categorie: 'comportementales',
    conseilReponse: 'Nuancez : vous appréciez l\'autonomie mais savez demander de l\'aide si nécessaire.',
    aEviter: '"J\'aime travailler seul et je n\'ai pas besoin d\'aide" — peut sembler isolationniste.',
    bonneAmorce: '"J\'apprécie pouvoir avancer de façon autonome, mais je sais reconnaître quand il est utile de solliciter…"',
  },
  {
    id: 34,
    question: 'Comment vous positionnez-vous face à la hiérarchie ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous respectez la hiérarchie tout en étant capable de proposer et d\'alerter si nécessaire.',
    aEviter: '"Je fais ce qu\'on me dit sans poser de questions" ou "j\'aime remettre en question toutes les décisions".',
    bonneAmorce: '"Je respecte la hiérarchie et la ligne de conduite fixée, tout en me permettant de proposer des idées ou d\'alerter si…"',
  },
  {
    id: 35,
    question: 'Qu\'est-ce qui vous distingue d\'un autre candidat ayant le même diplôme ?',
    categorie: 'motivations',
    conseilReponse: 'Mettez en avant votre expérience terrain, votre personnalité, vos projets spécifiques.',
    aEviter: '"Je suis travailleur" ou "je suis motivé" — des qualités génériques que tout le monde revendique.',
    bonneAmorce: '"Ce qui me distingue, c\'est [élément différenciant concret] comme [exemple]…"',
  },
  {
    id: 36,
    question: 'Qu\'est-ce qu\'une bonne journée de travail pour vous ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez ce qui vous anime : résolution de problèmes, collaboration, atteinte d\'objectifs.',
    aEviter: '"Une journée sans stress" — trop défensif et peu positif.',
    bonneAmorce: '"Une bonne journée pour moi, c\'est une où j\'ai pu [activité clé] et [résultat concret]…"',
  },
  {
    id: 37,
    question: 'Comment réagissez-vous quand vous recevez une critique ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous écoutez, que vous prenez du recul, et que vous tirez des leçons.',
    aEviter: '"Je ne prends pas bien la critique" ou "je suis très sensible" sans compenser.',
    bonneAmorce: '"Quand je reçois une critique, je prends d\'abord le temps d\'écouter sans réagir à chaud, puis je…"',
  },
  {
    id: 38,
    question: 'Avez-vous des exemples de projets innovants que vous avez initiés ?',
    categorie: 'competences',
    conseilReponse: 'Même un petit projet scolaire, associatif ou personnel peut illustrer votre initiative et créativité.',
    aEviter: 'Répondre non sans chercher à valoriser une initiative, même modeste.',
    bonneAmorce: '"Lors de [contexte], j\'ai proposé et mis en place [initiative], ce qui a conduit à…"',
  },
  {
    id: 39,
    question: 'Quelle est la différence entre vente BtoB et BtoC ?',
    categorie: 'competences',
    conseilReponse: 'Expliquez clairement : cycle de vente, interlocuteurs, décision d\'achat, relation.',
    aEviter: 'Confondre les deux ou ne pas pouvoir répondre à une question aussi fondamentale.',
    bonneAmorce: '"En BtoB, on vend à des entreprises avec un cycle long et plusieurs décisionnaires, tandis qu\'en BtoC…"',
  },
  {
    id: 40,
    question: 'Que savez-vous de nos concurrents ?',
    categorie: 'motivations',
    conseilReponse: 'Préparez toujours une connaissance du marché concurrentiel avant un entretien.',
    aEviter: '"Je n\'en sais pas trop" — manque de préparation flagrant.',
    bonneAmorce: '"D\'après mes recherches, vos principaux concurrents sont [noms] et ce qui vous différencie semble être…"',
  },
  {
    id: 41,
    question: 'Avez-vous déjà géré une réclamation client ?',
    categorie: 'comportementales',
    conseilReponse: 'Décrivez la situation, comment vous avez écouté, géré et résolu le problème.',
    aEviter: 'Inventer une situation ou dire non sans valoriser une expérience approchante.',
    bonneAmorce: '"Lors de [expérience], un client était mécontent de [situation]. J\'ai d\'abord écouté, puis proposé…"',
  },
  {
    id: 42,
    question: 'Comment définissez-vous le service client de qualité ?',
    categorie: 'competences',
    conseilReponse: 'Soyez précis : écoute, réactivité, empathie, résolution efficace, suivi.',
    aEviter: '"Sourire et être sympa" — trop superficiel pour un recruteur.',
    bonneAmorce: '"Pour moi, un service client de qualité, c\'est avant tout [valeur clé], comme quand…"',
  },
  {
    id: 43,
    question: 'Que faites-vous quand vous ne savez pas répondre à une question ?',
    categorie: 'comportementales',
    conseilReponse: 'Honnêteté, démarche proactive : vous cherchez, vous signalez et vous revenez avec une réponse.',
    aEviter: 'Inventer une réponse ou rester sans rien dire.',
    bonneAmorce: '"Quand je ne connais pas la réponse, je le dis honnêtement et je propose de trouver l\'information en…"',
  },
  {
    id: 44,
    question: 'Quel est votre rapport aux deadlines ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous les respectez et que vous anticipez les risques de dérapage.',
    aEviter: '"Je les respecte toujours" sans nuance ni exemple.',
    bonneAmorce: '"Pour moi les deadlines sont importantes. Quand je sens un risque de retard, je préviens tôt et…"',
  },
  {
    id: 45,
    question: 'Qu\'est-ce que vous apporteriez à notre équipe ?',
    categorie: 'motivations',
    conseilReponse: 'Citez des compétences ou qualités spécifiques en lien avec le poste et l\'équipe.',
    aEviter: 'Répondre de façon très générique sans lien avec le contexte de l\'entreprise.',
    bonneAmorce: '"Je pense que j\'apporterais [compétence / qualité] qui serait utile pour [contexte de l\'équipe ou du poste]…"',
  },
  {
    id: 46,
    question: 'Avez-vous déjà travaillé avec des outils CRM ?',
    categorie: 'competences',
    conseilReponse: 'Citez les outils que vous connaissez (Salesforce, HubSpot, Zoho…) et comment vous les avez utilisés.',
    aEviter: '"Non, jamais" si vous n\'avez pas cherché à apprendre au moins les bases.',
    bonneAmorce: '"J\'ai utilisé [outil] lors de [expérience] pour [usage précis]. J\'ai aussi entendu parler de…"',
  },
  {
    id: 47,
    question: 'Comment gérez-vous les priorités quand tout est urgent ?',
    categorie: 'comportementales',
    conseilReponse: 'Décrivez une méthode : matrice d\'urgence/importance, discussion avec le manager, découpage des tâches.',
    aEviter: '"Je fais tout en même temps" — peu efficace et peu crédible.',
    bonneAmorce: '"Face à des urgences multiples, je commence par évaluer l\'impact de chaque tâche et j\'en parle si besoin à…"',
  },
  {
    id: 48,
    question: 'Seriez-vous à l\'aise dans un environnement de travail multiculturel ?',
    categorie: 'comportementales',
    conseilReponse: 'Appuyez-vous sur des expériences réelles ou une ouverture d\'esprit documentée.',
    aEviter: '"Oui, j\'aime bien les gens différents" sans consistance.',
    bonneAmorce: '"Oui, j\'ai [expérience / côtoiement de cultures] ce qui m\'a appris à [attitude ou compétence]…"',
  },
  {
    id: 49,
    question: 'Comment vous tenez-vous informé(e) de l\'actualité du secteur ?',
    categorie: 'motivations',
    conseilReponse: 'Citez des sources concrètes : presse spécialisée, newsletters, podcasts, événements.',
    aEviter: '"Je lis des articles sur internet" sans précision — trop vague.',
    bonneAmorce: '"Je suis [source 1], [source 2] et je participe à [événement / réseau] pour rester informé(e) de…"',
  },
  {
    id: 50,
    question: 'Qu\'est-ce qui vous attire dans le fait d\'être en contact avec des clients ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez votre sens du service, votre goût pour les échanges humains, votre empathie.',
    aEviter: '"Rien de particulier" ou "parce que c\'est dans ma formation".',
    bonneAmorce: '"Ce qui me plaît dans la relation client, c\'est [dimension humaine / résolution de problèmes]…"',
  },
  {
    id: 51,
    question: 'Êtes-vous à l\'aise avec la prospection commerciale ?',
    categorie: 'competences',
    conseilReponse: 'Soyez honnête sur votre expérience, montrez votre motivation et vos méthodes.',
    aEviter: '"Je préfère que les clients viennent à moi" pour un poste commercial.',
    bonneAmorce: '"J\'ai eu l\'occasion de [démarcher / contacter] lors de [expérience] et j\'ai appris à…"',
  },
  {
    id: 52,
    question: 'Qu\'est-ce qu\'une négociation réussie pour vous ?',
    categorie: 'competences',
    conseilReponse: 'Montrez que vous visez une solution gagnant-gagnant, pas seulement votre intérêt.',
    aEviter: '"Obtenir ce que je veux" sans mentionner la satisfaction de l\'autre partie.',
    bonneAmorce: '"Une négociation réussie, c\'est quand les deux parties arrivent à un accord satisfaisant, comme lors de…"',
  },
  {
    id: 53,
    question: 'Quel a été votre plus grand défi académique ?',
    categorie: 'parcours',
    conseilReponse: 'Choisissez un défi réel, montrez comment vous l\'avez surmonté et ce que vous en avez retenu.',
    aEviter: 'Un défi trop banal ou trop catastrophique, présenté sans réflexion.',
    bonneAmorce: '"Le plus grand défi académique a été [situation]. Ce que j\'ai fait pour y faire face, c\'est…"',
  },
  {
    id: 54,
    question: 'Avez-vous des exemples d\'initiatives prises de votre propre chef ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous êtes proactif sans attendre qu\'on vous dise quoi faire.',
    aEviter: '"Je fais ce qu\'on me demande" — montre un manque d\'initiative.',
    bonneAmorce: '"Dans [contexte], j\'ai remarqué que [problème], j\'ai donc pris l\'initiative de [action] ce qui a…"',
  },
  {
    id: 55,
    question: 'Comment abordez-vous un nouveau projet dont vous ne connaissez pas le domaine ?',
    categorie: 'comportementales',
    conseilReponse: 'Décrivez votre démarche d\'apprentissage : benchmark, questions, formation rapide.',
    aEviter: '"Je plonge dedans sans réfléchir" ou "je ne sais pas encore".',
    bonneAmorce: '"Face à un domaine inconnu, ma première étape est de [recherche / question / benchmark]. Ensuite…"',
  },
  {
    id: 56,
    question: 'Comment travaillez-vous en télétravail ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez votre discipline, vos outils de communication et votre autonomie.',
    aEviter: '"Je suis moins productif(ve) chez moi" — manque de réassurance pour l\'employeur.',
    bonneAmorce: '"En télétravail, je maintiens mes horaires, utilise [outils de communication] et reste disponible pour…"',
  },
  {
    id: 57,
    question: 'Que feriez-vous si vous étiez en désaccord avec la décision d\'un supérieur ?',
    categorie: 'comportementales',
    conseilReponse: 'Exprimez que vous partagez votre point de vue respectueusement, puis appliquez la décision finale.',
    aEviter: '"J\'obéis sans discuter" ou "je refuse de suivre une décision que je juge mauvaise".',
    bonneAmorce: '"Je partagerais mon point de vue en privé avec des arguments clairs, mais si la décision est maintenue…"',
  },
  {
    id: 58,
    question: 'Qu\'est-ce qu\'un bon management pour vous ?',
    categorie: 'motivations',
    conseilReponse: 'Mentionnez des éléments concrets : clarté des objectifs, feedback régulier, autonomie, reconnaissance.',
    aEviter: '"Un manager qui nous laisse tranquilles" — trop passif.',
    bonneAmorce: '"Pour moi, un bon manager est quelqu\'un qui [qualité 1] et [qualité 2], comme [exemple ou valeur]…"',
  },
  {
    id: 59,
    question: 'Avez-vous déjà travaillé sur un projet avec des contraintes budgétaires fortes ?',
    categorie: 'competences',
    conseilReponse: 'Donnez un exemple scolaire ou associatif si vous n\'avez pas d\'expérience pro, et montrez comment vous avez géré.',
    aEviter: 'Répondre non sans chercher d\'analogie.',
    bonneAmorce: '"Lors de [projet], nous avions un budget limité de [X]. J\'ai dû faire des choix comme…"',
  },
  {
    id: 60,
    question: 'Quelle est votre vision de la relation commerciale à long terme ?',
    categorie: 'competences',
    conseilReponse: 'Mettez en avant la fidélisation, la confiance, le suivi régulier et la valeur ajoutée dans la durée.',
    aEviter: '"Vendre et passer à la suite" — vision court-termiste peu adaptée à la relation client.',
    bonneAmorce: '"Pour moi, une relation commerciale durable repose sur [confiance / valeur / suivi]. Un exemple concret serait…"',
  },
  {
    id: 61,
    question: 'Comment réagissez-vous si vous ratez un objectif ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous analysez les causes, tirez des leçons et vous ajustez.',
    aEviter: '"Je suis dévasté(e)" ou "ça ne m\'arrive jamais".',
    bonneAmorce: '"Si je rate un objectif, je commence par comprendre pourquoi, puis je [ajustement], comme lors de…"',
  },
  {
    id: 62,
    question: 'Quels types de managers avez-vous eu et comment vous êtes-vous adapté(e) ?',
    categorie: 'parcours',
    conseilReponse: 'Montrez votre adaptabilité sans critiquer vos anciens responsables.',
    aEviter: 'Critiquer nommément un ancien manager ou montrer de la rigidité.',
    bonneAmorce: '"J\'ai eu des styles de management différents. Par exemple, avec [style X], j\'ai appris à…"',
  },
  {
    id: 63,
    question: 'Qu\'est-ce qu\'un client difficile pour vous et comment le gérez-vous ?',
    categorie: 'competences',
    conseilReponse: 'Définissez "difficile" (exigeant, agressif, indécis) et donnez une technique de gestion.',
    aEviter: '"Je les évite" ou une réponse trop vague.',
    bonneAmorce: '"Un client difficile peut être quelqu\'un d\'agressif ou d\'indécis. Dans ce cas, j\'essaie de…"',
  },
  {
    id: 64,
    question: 'Comment définissez-vous le travail bien fait ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez des critères de qualité précis : respect des délais, des objectifs, de la méthode, du résultat attendu.',
    aEviter: '"Faire ce qu\'on m\'a demandé" — trop passif et peu ambitieux.',
    bonneAmorce: '"Pour moi, un travail bien fait, c\'est un travail qui répond à [critère 1] et [critère 2], comme…"',
  },
  {
    id: 65,
    question: 'Que pensez-vous de l\'intelligence artificielle dans votre futur métier ?',
    categorie: 'competences',
    conseilReponse: 'Montrez que vous êtes informé(e) des enjeux et positif(ve) sur l\'adaptation plutôt que la crainte.',
    aEviter: '"Ça va remplacer tout le monde" ou "ça ne change rien pour moi".',
    bonneAmorce: '"Je pense que l\'IA va transformer certaines tâches, notamment [exemple], ce qui me pousse à développer…"',
  },
  {
    id: 66,
    question: 'Avez-vous déjà présenté des résultats à une direction ?',
    categorie: 'competences',
    conseilReponse: 'Valorisez même une présentation scolaire de groupe, un bilan d\'association, ou un rapport de stage.',
    aEviter: '"Non, pas encore" sans chercher d\'équivalent.',
    bonneAmorce: '"Lors de [contexte], j\'ai présenté [sujet] à [public]. J\'ai préparé [méthode] et j\'ai obtenu…"',
  },
  {
    id: 67,
    question: 'Comment vous décrirait votre meilleur ami(e) en 3 mots ?',
    categorie: 'comportementales',
    conseilReponse: 'Choisissez des qualités cohérentes avec votre profil professionnel et soyez prêt(e) à les illustrer.',
    aEviter: 'Des qualités trop superficielles ("sympa, cool, rigolo") ou incohérentes avec le poste.',
    bonneAmorce: '"Il/elle dirait que je suis [mot 1], [mot 2] et [mot 3]. Ce qui se reflète dans [exemple concret]…"',
  },
  {
    id: 68,
    question: 'Quelle lecture professionnelle ou actualité vous a marqué(e) récemment ?',
    categorie: 'motivations',
    conseilReponse: 'Préparez une réponse à l\'avance en lien avec le secteur de l\'entreprise.',
    aEviter: '"Je ne lis pas vraiment" ou une réponse non liée au domaine professionnel.',
    bonneAmorce: '"J\'ai lu récemment [article / livre / podcast] sur [sujet], et ce qui m\'a marqué(e), c\'est…"',
  },
  {
    id: 69,
    question: 'Quelle serait votre réaction si votre contrat était prolongé ou non renouvelé ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez que vous vous concentrez sur l\'apport de valeur pendant la mission, et que vous envisagez l\'avenir avec sérénité.',
    aEviter: '"Je serais anéanti(e)" ou "je m\'en fiche, j\'ai d\'autres options".',
    bonneAmorce: '"Je ferais le maximum pour que ma contribution soit visible et mérite une suite. Sinon, je repartirais avec…"',
  },
  {
    id: 70,
    question: 'Comment construisez-vous votre réseau professionnel ?',
    categorie: 'motivations',
    conseilReponse: 'Mentionnez LinkedIn, événements pro, associations, anciens camarades ou professeurs.',
    aEviter: '"Je n\'en ai pas vraiment" ou un réseau purement passif.',
    bonneAmorce: '"Je développe mon réseau en [méthode concrète], notamment via [exemple de contact ou événement]…"',
  },
  {
    id: 71,
    question: 'Qu\'est-ce que vous apportez à un projet en dehors de vos compétences techniques ?',
    categorie: 'motivations',
    conseilReponse: 'Parlez de soft skills : enthousiasme, organisation, communication, humour, leadership situationnel.',
    aEviter: 'Se limiter aux compétences techniques déjà listées dans le CV.',
    bonneAmorce: '"En dehors des compétences techniques, j\'apporte [qualité], ce qui s\'est manifesté lors de…"',
  },
  {
    id: 72,
    question: 'Quel projet de fin d\'études ou travail de recherche avez-vous réalisé ?',
    categorie: 'parcours',
    conseilReponse: 'Expliquez le sujet, la méthode, les résultats et ce que vous en avez appris.',
    aEviter: 'Un résumé trop technique sans lien avec les compétences professionnelles attendues.',
    bonneAmorce: '"Mon projet portait sur [sujet]. L\'enjeu était de… J\'ai utilisé [méthode] et j\'ai abouti à…"',
  },
  {
    id: 73,
    question: 'Avez-vous l\'habitude de travailler sur plusieurs sujets en parallèle ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous savez switcher d\'un sujet à l\'autre sans perdre le fil ni la qualité.',
    aEviter: '"Non, j\'aime faire une seule chose à la fois" — peut sembler peu adaptable.',
    bonneAmorce: '"Oui, lors de [expérience], je gérais [X sujets] simultanément. Ma façon de procéder était de…"',
  },
  {
    id: 74,
    question: 'Quelle est votre plus grande force dans un contexte de travail sous pression ?',
    categorie: 'comportementales',
    conseilReponse: 'Citez une vraie qualité (calme, méthode, priorisation) et illustrez avec un exemple.',
    aEviter: '"Je travaille bien sous pression" sans dire pourquoi ni comment.',
    bonneAmorce: '"Ma principale force dans ce contexte est [qualité], qui m\'a aidé lors de [situation concrète]…"',
  },
  {
    id: 75,
    question: 'Avez-vous déjà coaché ou aidé un pair à progresser ?',
    categorie: 'comportementales',
    conseilReponse: 'Donnez un exemple concret, même informel (aide à un camarade, tutoring, mentorat scolaire).',
    aEviter: 'Répondre non sans chercher d\'exemple dans vos activités passées.',
    bonneAmorce: '"Lors de [contexte], un camarade ou collègue avait du mal avec [sujet], et j\'ai aidé en…"',
  },
  {
    id: 76,
    question: 'Pensez-vous que les stages donnent une vraie image du monde professionnel ?',
    categorie: 'motivations',
    conseilReponse: 'Nuancez : les stages offrent un aperçu précieux mais partiel. Montrez votre maturité de réflexion.',
    aEviter: '"Oui, complètement" ou "non, ça ne reflète rien de réel".',
    bonneAmorce: '"Un stage donne une vraie immersion, mais il reste partiel. Ce que j\'en ai retenu de précieux, c\'est…"',
  },
  {
    id: 77,
    question: 'Quel est votre mode de fonctionnement préféré : en open space ou en bureau individuel ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez votre adaptabilité. Chacun a des préférences, mais l\'essentiel est de fonctionner dans les deux contextes.',
    aEviter: '"J\'ai besoin de calme absolu" si le poste est en open space, ou l\'inverse.',
    bonneAmorce: '"J\'apprécie les deux selon la mission. Pour les tâches de concentration, je préfère… mais j\'aime aussi…"',
  },
  {
    id: 78,
    question: 'Comment gérez-vous votre énergie sur une journée de travail intense ?',
    categorie: 'comportementales',
    conseilReponse: 'Mentionnez des pratiques concrètes : pauses, organisation, alimentation, gestion des temps forts.',
    aEviter: '"Je ne sais pas" ou "le café" sans réflexion sur votre propre gestion.',
    bonneAmorce: '"Pour maintenir mon énergie, j\'organise mes tâches de façon à… et je prends soin de…"',
  },
  {
    id: 79,
    question: 'Pourquoi êtes-vous en recherche de stage maintenant ?',
    categorie: 'parcours',
    conseilReponse: 'Expliquez clairement votre situation académique et ce que le stage doit vous apporter.',
    aEviter: '"C\'est obligatoire dans ma formation" — trop neutre, sans montrer d\'envie.',
    bonneAmorce: '"Je suis à [niveau] et ce stage représente pour moi l\'occasion de [objectif concret], notamment en…"',
  },
  {
    id: 80,
    question: 'Quels sont vos projets professionnels après votre formation ?',
    categorie: 'motivations',
    conseilReponse: 'Montrez une vision claire sans être rigide : secteur cible, type de poste, développement de compétences.',
    aEviter: '"Je ne sais pas encore" ou un projet complètement hors du domaine de l\'entreprise.',
    bonneAmorce: '"Après ma formation, j\'aimerais [poste / secteur], en continuant à développer [compétence]…"',
  },
  {
    id: 81,
    question: 'Quel est votre rapport aux outils bureautiques (Excel, PowerPoint, Word) ?',
    categorie: 'competences',
    conseilReponse: 'Soyez précis sur votre niveau réel. Excel : tableaux croisés ? Formules ? Macros ? PowerPoint : mise en page pro ?',
    aEviter: '"Je sais m\'en servir" sans précision de niveau.',
    bonneAmorce: '"Sur Excel, je maîtrise [fonctions], et sur PowerPoint j\'ai l\'habitude de créer [type de support]…"',
  },
  {
    id: 82,
    question: 'Comment gérez-vous les situations où vous devez travailler avec quelqu\'un que vous n\'appréciez pas ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez professionnalisme et maturité : vous séparez le relationnel du professionnel.',
    aEviter: '"Je l\'évite" ou "je ne sais pas, ça ne m\'est jamais arrivé".',
    bonneAmorce: '"Dans ce cas, je me concentre sur la mission et maintiens une relation professionnelle courtoise…"',
  },
  {
    id: 83,
    question: 'Avez-vous déjà participé à la rédaction d\'un rapport ou document structuré ?',
    categorie: 'competences',
    conseilReponse: 'Valorisez les rapports de stage, projets de groupe, mémoires ou comptes rendus.',
    aEviter: '"Non, pas vraiment" si vous avez rédigé des projets scolaires.',
    bonneAmorce: '"Oui, lors de [contexte], j\'ai rédigé [type de document] en structurant [méthode de rédaction]…"',
  },
  {
    id: 84,
    question: 'Comment réagissez-vous si on vous confie une mission que vous n\'aimez pas ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous l\'exécutez professionnellement, tout en étant capable de partager vos préférences à terme.',
    aEviter: '"Je refuse ce genre de mission" ou "ça ne m\'arrive jamais".',
    bonneAmorce: '"Je l\'effectue sérieusement même si ce n\'est pas ma préférence. Je peux exprimer mes aspirations…"',
  },
  {
    id: 85,
    question: 'Comment évaluez-vous la qualité de votre propre travail ?',
    categorie: 'competences',
    conseilReponse: 'Citez des critères concrets : relecture, comparaison aux attentes, feedback demandé.',
    aEviter: '"Je sais si c\'est bon ou pas" sans méthode ni critères.',
    bonneAmorce: '"Je commence par vérifier que [critère 1] et [critère 2] sont respectés, puis je demande un retour à…"',
  },
  {
    id: 86,
    question: 'Quel est votre rapport à la confidentialité des informations ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous comprenez l\'importance de la confidentialité en entreprise et que vous la respectez.',
    aEviter: '"Ça dépend des informations" sans précision.',
    bonneAmorce: '"Je suis conscient(e) que certaines informations sont sensibles et je respecte la règle de…"',
  },
  {
    id: 87,
    question: 'Avez-vous déjà fait une veille concurrentielle ou sectorielle ?',
    categorie: 'competences',
    conseilReponse: 'Expliquez comment vous avez réalisé cette veille (sources, fréquence, outils) et ce que vous en avez tiré.',
    aEviter: '"Non, jamais" si vous suivez l\'actualité de votre domaine d\'une façon ou d\'une autre.',
    bonneAmorce: '"Lors de [contexte], j\'ai mis en place une veille sur [sujet] en utilisant [sources] et j\'en ai tiré…"',
  },
  {
    id: 88,
    question: 'Qu\'est-ce qu\'un bon pitch commercial ?',
    categorie: 'competences',
    conseilReponse: 'Donnez les éléments clés : accroche, valeur ajoutée, bénéfices client, appel à l\'action.',
    aEviter: 'Une réponse floue ou hors sujet.',
    bonneAmorce: '"Un bon pitch commercial doit d\'abord accrocher l\'attention, présenter clairement [valeur], et…"',
  },
  {
    id: 89,
    question: 'Comment vous intégrez-vous dans une nouvelle équipe ?',
    categorie: 'comportementales',
    conseilReponse: 'Décrivez une démarche proactive : observer, poser des questions, proposer votre aide, montrer votre motivation.',
    aEviter: '"J\'attends qu\'on vienne vers moi" — passif.',
    bonneAmorce: '"Lors de ma prise de poste, je prends le temps d\'observer, de me présenter, et je propose rapidement…"',
  },
  {
    id: 90,
    question: 'Seriez-vous à l\'aise pour représenter l\'entreprise lors d\'un salon ou événement ?',
    categorie: 'competences',
    conseilReponse: 'Montrez votre aisance relationnelle et votre capacité à incarner les valeurs de l\'entreprise.',
    aEviter: '"Je ne suis pas très à l\'aise avec les inconnus" pour un poste commercial ou de communication.',
    bonneAmorce: '"Oui, j\'ai déjà [représenté une association / un projet] lors de [événement], et j\'ai aimé parce que…"',
  },
  {
    id: 91,
    question: 'Qu\'est-ce que vous faites quand vous avez terminé vos tâches avant la fin de journée ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez de l\'initiative : vous cherchez à vous rendre utile, vous vous formez, vous anticipez les prochaines tâches.',
    aEviter: '"Je me repose" ou "je regarde mon téléphone".',
    bonneAmorce: '"Je signale que j\'ai terminé et je propose mon aide, ou j\'en profite pour avancer sur [sujet annexe]…"',
  },
  {
    id: 92,
    question: 'Quelle est la dernière compétence que vous avez apprise par vous-même ?',
    categorie: 'competences',
    conseilReponse: 'Montrez votre curiosité intellectuelle et votre autonomie dans l\'apprentissage.',
    aEviter: '"Je ne me souviens pas" ou une compétence sans lien avec un contexte d\'apprentissage.',
    bonneAmorce: '"Récemment, j\'ai appris [compétence] de façon autonome via [méthode ou outil]. Ce qui m\'a motivé, c\'est…"',
  },
  {
    id: 93,
    question: 'Avez-vous une expérience dans la gestion de projets ?',
    categorie: 'competences',
    conseilReponse: 'Valorisez des projets scolaires, associatifs ou personnels avec une structure (objectif, planning, équipe, résultat).',
    aEviter: '"Non, pas vraiment" si vous avez déjà organisé quoi que ce soit à plusieurs.',
    bonneAmorce: '"Lors de [contexte], j\'ai coordonné un projet dont l\'objectif était [X]. J\'ai géré [aspect] et le résultat a été…"',
  },
  {
    id: 94,
    question: 'Comment réagissez-vous si vous êtes en désaccord avec un client ?',
    categorie: 'comportementales',
    conseilReponse: 'Montrez que vous écoutez, expliquez calmement votre position, et cherchez une solution.',
    aEviter: '"Le client a toujours raison" — trop complaisant — ou "je défends ma position coûte que coûte".',
    bonneAmorce: '"Je commence par écouter pour comprendre son point de vue, puis j\'explique calmement [ma position]…"',
  },
  {
    id: 95,
    question: 'Qu\'est-ce qui vous frustre dans un contexte professionnel ?',
    categorie: 'comportementales',
    conseilReponse: 'Citez quelque chose de réel mais montrez comment vous le gérez de façon constructive.',
    aEviter: 'Critiquer l\'organisation, les collègues ou la hiérarchie de façon générale.',
    bonneAmorce: '"Ce qui peut me frustrer, c\'est [situation réelle], mais j\'apprends à le gérer en…"',
  },
  {
    id: 96,
    question: 'Avez-vous déjà pris la parole en public ?',
    categorie: 'competences',
    conseilReponse: 'Valorisez toute expérience : exposé, présentation, event associatif, Toastmasters, etc.',
    aEviter: '"Non, je suis très timide" sans montrer de volonté de progresser.',
    bonneAmorce: '"Oui, lors de [contexte], j\'ai présenté [sujet] à [public]. Ce que j\'en ai retenu sur ma façon de…"',
  },
  {
    id: 97,
    question: 'Que faites-vous pour continuer à apprendre dans votre domaine ?',
    categorie: 'motivations',
    conseilReponse: 'Citez des pratiques concrètes et régulières : podcasts, MOOC, lectures, certifications, événements.',
    aEviter: '"Rien de particulier" ou une liste sans exemples.',
    bonneAmorce: '"Pour me tenir à jour, j\'utilise [pratique concrète], notamment sur [thème], comme récemment…"',
  },
  {
    id: 98,
    question: 'Quel est votre niveau d\'anglais professionnel ?',
    categorie: 'competences',
    conseilReponse: 'Soyez honnête et précis : niveau TOEIC, expérience d\'utilisation en contexte pro, échanges réguliers.',
    aEviter: '"Courant" si vous n\'avez que des bases scolaires.',
    bonneAmorce: '"Mon niveau est [niveau], j\'ai utilisé l\'anglais dans [contexte] et je continue à l\'entretenir en…"',
  },
  {
    id: 99,
    question: 'Quel type de management vous convient le mieux ?',
    categorie: 'motivations',
    conseilReponse: 'Nuancez selon le contexte : autonomie + feedback régulier. Montrez que vous vous adaptez.',
    aEviter: '"Je veux être totalement libre" ou "j\'ai besoin d\'être très encadré(e)" — les deux extrêmes interrogent.',
    bonneAmorce: '"J\'apprécie un management qui me donne de l\'autonomie tout en étant disponible pour un feedback régulier…"',
  },
  {
    id: 100,
    question: 'Avez-vous quelque chose à ajouter pour conclure cet entretien ?',
    categorie: 'motivations',
    conseilReponse: 'Profitez de cette ouverture pour réaffirmer votre motivation, mentionner un point non abordé, ou poser une question.',
    aEviter: '"Non, c\'est bon" — vous laissez passer une dernière chance de vous démarquer.',
    bonneAmorce: '"Oui, je voudrais ajouter que [point important], et je suis vraiment enthousiaste à l\'idée de…"',
  },
]

export const formulationsCV = [
  { type: 'Compétence commerciale', exemple: 'Développé un portefeuille de 30 clients prospects via prospection téléphonique et email' },
  { type: 'Compétence organisationnelle', exemple: 'Coordonné la logistique d\'un événement de 200 personnes en autonomie' },
  { type: 'Compétence relationnelle', exemple: 'Animé des sessions de formation pour 15 collaborateurs sur un nouveau logiciel CRM' },
  { type: 'Compétence analytique', exemple: 'Analysé les données de vente hebdomadaires et produit des rapports de performance pour la direction' },
  { type: 'Résultat chiffré', exemple: 'Contribué à une augmentation de 12 % du taux de satisfaction client sur le trimestre' },
  { type: 'Gestion de projet', exemple: 'Piloté un projet de refonte d\'un outil interne, en respectant le planning et le budget initial' },
  { type: 'Communication', exemple: 'Rédigé une newsletter mensuelle à destination de 500 abonnés avec un taux d\'ouverture de 35 %' },
  { type: 'Initiative', exemple: 'Proposé et mis en place une procédure de suivi client qui a réduit les relances de 40 %' },
  { type: 'Compétence digitale', exemple: 'Géré les réseaux sociaux de l\'entreprise (LinkedIn, Instagram) avec une croissance de 25 % des abonnés' },
  { type: 'Objectif professionnel', exemple: 'Candidat en PGE1 cherchant à développer des compétences opérationnelles en marketing digital dans une PME dynamique' },
  { type: 'Compétence interculturelle', exemple: 'Travaillé avec une équipe internationale (France, Espagne, Maroc) dans le cadre d\'un projet export' },
  { type: 'Adaptation', exemple: 'Intégré rapidement une nouvelle équipe lors d\'un remplacement de 3 semaines sans supervision' },
]
